image: node:latest

before_script:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 'thinkingpandas.com' >> ~/.ssh/known_hosts
  - npm install
  - (cd web ; npm install ; npm run build)
  - npm run build:api-doc

cache:
  paths:
    - node_modules/
    - web/node_modules/

stages:
  - deploy

deploy to production:
  stage: deploy
  script:
    - rm -rf .git
    - git init
    - git config --global user.name "Justin Sanciangco"
    - git config --global user.email "justin@thinkingpandas.com"
    - git add .
    - git add -f build/
    - git add -f api-doc/swagger.json
    - git rm --cached -r web
    - git commit -m 'deployment'
    - git remote add dokku dokku@thinkingpandas.com:expense-manager
    - git push dokku master --force
